var decks = {
default_deck : [
"Personaje: Monstruo marino (Dagon)",
"Objeto: Necronomicon",
"Acontecimiento: Ritual de sacrificio",
"Lugar: Ruinas civilización antigua",
"Personaje: Gente Pez",
"Detalle: Branquias",
"Lugar: Garganta profunda",
"Lugar: En el fondo del mar",
"Aspecto: Pagano",
"Objeto: Símbolo Arcano",
"Lugar: Faro",
"Personaje: Arqueólogo",
"Objeto: Arpón",
"Lugar: Playa",
"Personaje: Párroco local",
"Detalle: Temporal (lluvia y viento)",
"Aspecto: Cenagoso",
"Lugar: Pueblo costero",
"Objeto: Barca de pescador",
"Acontecimiento: Metamorfosis",
"Acontecimiento: Naufragio de un buque",
"Personaje: Marinero",
"Objeto: Estatuilla",
"Acontecimiento: Cefalópodos",
"Personaje: Detective",
"Aspecto: Gomoso",
"Detalle: Ruido de chapoteo",
"Personaje: Escritor de novelas de terror",
"Detalle: Hombres y mujeres desnudos",
"Objeto: Cuchillo",
"Lugar: Buhardilla",
"Lugar: Vieja mansión",
"Personaje: Turista",
"Detalle: Oscuridad",
"Aspecto: Sangriento",
"Lugar: Hotel",
"Acontecimiento: Mordisco",
"Personaje: Agente de la ley"
], 
blade_runner_deck : [
"Lugar: Tyrell Corporation",
"Acontecimiento: Entrevista con el Dr, Eldon Tyrell",
"Personaje: Replicante Nexus-6",
"Objeto: Máquina Voight-Kampff",
"Objeto: Unicornio de origami",
"Personaje: Blade Runner",
"Aspecto: Cruel",
"Acontecimiento: Lucha en la azotea",
"Lugar: Laboratorio genético",
"Detalle: Futuro distópico",
"Objeto: Fotografías en blanco y negro",
"Aspecto: Misericordioso",
"Lugar: Apartamentos Bradbury",
"Acontecimiento: Envejecimiento acelerado",
"Detalle: Kippel",
"Lugar: Yukon Hotel",
"Objeto: Spinner",
"Aspecto: Solitario",
"Personaje: Ingeniero Genético",
"Personaje: Bailarina exótica",
"Lugar: Club de striptease",
"Objeto: Caja de cerillas",
"Detalle: Sueño con unicornio",
"Acontecimiento: Persecución",
"Personaje: Traficante",
"Objeto: Animoide",
"Lugar: Tienda de animales exóticos",
"Lugar: Chinatown",
"Personaje: Magnate",
"Personaje: Oficial de Policía",
"Detalle: Cyberpunk",
"Aspecto: Escéptico",
"Objeto: Revolver",
"Aspecto: Melancólico",
"Personaje: Cazarecompensas",
"Objeto: Bote de fármacos",
"Lugar: Red de alcantarillado",
"Detalle: Tormenta sucia"
], 
antartida_deck : [
"Personaje: Jefe de Expedición",
"Personaje: Parásito Astral",
"Aspecto: Inhumano",
"Acontecimiento: Lluvia de meteoritos",
"Detalle: Las estrellas",
"Objeto: Diario (de la expedición)",
"Lugar: Módulo científico",
"Personaje: Comandante",
"Objeto: Botiquín de primeros auxilios",
"Lugar: Módulo de enfermería",
"Personaje: Oficial Médico",
"Lugar: Hangar (máquina quita-nieves y helicóptero Bell UH-1H Huey)",
"Personaje: Guía Polar",
"Acontecimiento: Ventarrón Katabático",
"Acontecimiento: Sabotaje",
"Lugar: Módulo de talleres y mantenimiento",
"Personaje: Mecánico",
"Lugar: Zona de extracción",
"Detalle: Olor a azufre",
"Personaje: Técnico",
"Personaje: Geólogo",
"Personaje: Ingeniero de Minas y perforación",
"Objeto: Arma",
"Acontecimiento: Bandada de págalos asesinos",
"Objeto: Tesoro",
"Detalle: Ruidos Extraños",
"Personaje: Astrofísico",
"Personaje: Cámara de televisión",
"Detalle: Gelatinoso",
"Acontecimiento: Síntomas de embarazo",
"Objeto: Máquina quita-nieves (bulldozer escavadora modelo Skidozer 252 G modificado)",
"Personaje: Aventurero polar",
"Aspecto: Paranoico",
"Lugar: Módulo de vida (cotidiana)",
"Objeto: Radio",
"Acontecimiento: Llamada de radio",
"Aspecto: Inhóspito",
"Detalle: Cristales rotos",
"Aspecto: Letal",
"Detalle: Rugido",
"Aspecto: Resucitado",
"Aspecto: Miedo a lo desconocido"
],
omerta_deck:[
"Acontecimiento: Murder Inc. (Sindicato del crimen)",
"Personaje: Gángster",
"Objeto: Thompson",
"Lugar: Casino ilegal",
"Personaje: Corredor de apuestas",
"Acontecimiento: Funeral",
"Lugar: Cementerio",
"Detalle: Protección de Testigos",
"Objeto: Rolls Royce Silver Wraith",
"Lugar: Comisaría de Policía",
"Personaje: Policía",
"Detalle: Brutalidad Policial",
"Acontecimiento: Lluvia de balas",
"Aspecto: Violento",
"Objeto: 357 Magnum (revolver)",
"Lugar: Club de Jazz",
"Personaje: Femme Fatale",
"Detalle: Asunto extramarital",
"Detalle: Amor a primera vista",
"Acontecimiento: Guerra de clanes",
"Personaje: Sicario",
"Acontecimiento: Ajuste de cuentas",
"Aspecto: Italo-americano",
"Detalle: Infringiendo las reglas",
"Objeto: Libro de cuentas",
"Personaje: Abogado",
"Detalle: Chivatazo",
"Personaje: Paparazzi",
"Acontecimiento: Soborno",
"Lugar: Estación de tren",
"Personaje: Detective Privado",
"Lugar: Restaurante",
"Acontecimiento: Corrupción política",
"Aspecto: Leal",
"Objeto: Maletín con dinero",
"Objeto: Cocktail Molotov",
"Aspecto: Diligente",
"Personaje: Prostituta"  
],
abismal_deck: [
"Personaje: Experto lingüista",
"Acontecimiento: Contacto alienígena",
"Personaje: Alien",
"Lugar: Dentro del Abismo",
"Aspecto: Miedo a lo desconocido",
"Personaje: Biólogo Marino",
"Acontecimiento: Atacado por un monstruo marino",
"Personaje: Calamar gigante",
"Lugar: Cueva submarina",
"Personaje: Astrofísico",
"Acontecimiento: Tsunami",
"Lugar: En la profundidad del océano",
"Objeto: Batiscafo",
"Detalle: Incomunicado",
"Personaje: Buzo",
"Objeto: Equipo pesado de buceo",
"Detalle: Falta de oxígeno",
"Aspecto: Paranoico",
"Objeto: Pistola",
"Lugar: Arrecife de coral",
"Detalle: Festival de luces y colores",
"Objeto: Linterna",
"Aspecto: Claustrofóbico",
"Acontecimiento: Alucinaciones",
"Lugar: Buque hundido",
"Detalle: Hiperventilación",
"Lugar: Laboratorio",
"Objeto: Aguja hipodérmica",
"Objeto: Desfibrilador",
"Acontecimiento: Convulsiones",
"Personaje: Militar marina EE.UU",
"Lugar: Cámara de descompresión",
"Lugar: Cresta rocosa",
"Personaje: Banco de medusas",
"Personaje: Psicólogo",
"Detalle: Pánico a la oscuridad",
"Aspecto: Locura",
"Detalle: Producto de la imaginación"  
],
sherlock_deck: [
"Personaje: Detective Consultor",
"Lugar: 221b Baker Street",
"Acontecimiento: Otoño de terror",
"Personaje: Asesino en serie",
"Lugar: Whitechapel",
"Objeto: Lupa",
"Aspecto: Inteligente",
"Objeto: Escalpelo",
"Detalle: Rastro de sangre",
"Aspecto: Sangriento",
"Lugar: Buckingham Palace",
"Personaje: Inspector Jefe de Policía",
"Acontecimiento: Suceso sobrenatural",
"Detalle: Ruidos Extraños",
"Lugar: Club Diógenes",
"Personaje: Femme Fatale",
"Detalle: Smog (niebla como una sopa de guisante)",
"Acontecimiento: Cena de gala",
"Personaje: Aristócrata",
"Acontecimiento: Entrevista con el comisionado",
"Objeto: Carruaje",
"Detalle: Traqueteo incesante",
"Aspecto: Anticuado",
"Lugar: Real Sociedad Geográfica",
"Personaje: Explorador",
"Personaje: Médico",
"Personaje: Reportero sensacionalista (Periodista)",
"Aspecto: Misterioso",
"Personaje: Artista",
"Detalle: Luz de gas",
"Lugar: Ten Bells",
"Objeto: Sabueso",
"Personaje: Rufián",
"Acontecimiento: Persiguiendo al dragón (en un fumadero de opio)",
"Objeto: Opio (o Morfina)",
"Personaje: Bailarina",
"Personaje: Prostituta",
"Detalle: Grito de pavor"  
]

}
